import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Calendar } from "@/components/ui/calendar";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FileText, Download, TrendingUp, Crown, Lock } from "lucide-react";
import Navigation from "@/components/Navigation";

const Reports = () => {
  const [selectedDate, setSelectedDate] = useState<Date | undefined>(new Date());
  const [reportType, setReportType] = useState("30-day");

  const sampleMetrics = {
    biohackherAge: { current: 34, trend: -2 },
    sleepScore: { current: 78, trend: 5 },
    hrv: { current: 65, trend: 8 },
    proteinIntake: { current: 85, trend: 12 },
    symptomScore: { current: 25, trend: -15 }
  };

  const reportData = {
    "30-day": {
      title: "30-Day Longevity Report", 
      period: "March 2024",
      highlights: [
        "Biohackher Age improved by 2 years",
        "Sleep quality increased 15%", 
        "Hot flash frequency reduced 40%",
        "Protein targets met 85% of days"
      ],
      recommendations: [
        "Continue current sleep optimisation protocol",
        "Increase cold exposure frequency to 4x/week",
        "Add leucine supplementation to plant-based meals"
      ]
    },
    "90-day": {
      title: "90-Day Comprehensive Report",
      period: "Jan-Mar 2024", 
      highlights: [
        "Overall wellness score improved 32%",
        "Energy levels stabilized across cycle phases",
        "Reduced inflammatory markers by 25%",
        "Achieved target protein intake 80% of quarter"
      ],
      recommendations: [
        "Consider HRT consultation for symptom optimisation",
        "Implement structured strength training program",
        "Add targeted micronutrient testing"
      ]
    }
  };

  const currentReport = reportData[reportType as keyof typeof reportData];

  const generateReport = () => {
    // In real app, this would generate and download actual PDF
    const reportContent = `
BIOHACKHER LONGEVITY REPORT
${currentReport.title}
Period: ${currentReport.period}

EXECUTIVE SUMMARY
Your biohacking journey shows significant progress across multiple biomarkers.
Key improvements in sleep optimisation and symptom management protocols.

BIOHACKHER AGE ANALYSIS
Current Age: ${sampleMetrics.biohackherAge.current} years
Improvement: ${Math.abs(sampleMetrics.biohackherAge.trend)} years younger
Factors: Sleep quality, HRV training, nutrition optimisation

KEY METRICS SUMMARY
• Sleep Score: ${sampleMetrics.sleepScore.current}% (↑${sampleMetrics.sleepScore.trend}%)
• HRV: ${sampleMetrics.hrv.current}ms (↑${sampleMetrics.hrv.trend}%)  
• Protein Compliance: ${sampleMetrics.proteinIntake.current}% (↑${sampleMetrics.proteinIntake.trend}%)
• Symptom Score: ${sampleMetrics.symptomScore.current}/100 (↓${Math.abs(sampleMetrics.symptomScore.trend)}%)

HIGHLIGHTS
${currentReport.highlights.map(h => `• ${h}`).join('\n')}

RECOMMENDATIONS
${currentReport.recommendations.map(r => `• ${r}`).join('\n')}

PROTOCOLS COMPLETED
• Red Light Therapy: 24/30 sessions
• Cold Exposure: 18/30 sessions  
• HRV Breathwork: 28/30 sessions
• Sleep Optimisation: 27/30 nights

Generated by Biohackher - Women's Longevity Coach
Report ID: BH-${Date.now()}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportType}-biohackher-report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2 gradient-text">Progress Reports</h1>
          <p className="text-muted-foreground">
            Comprehensive analysis of your biohacking journey and longevity metrics
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Report Configuration */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Generate Report</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-sm font-medium mb-2 block">Report Type</label>
                  <select 
                    value={reportType}
                    onChange={(e) => setReportType(e.target.value)}
                    className="w-full p-2 border rounded-md"
                  >
                    <option value="30-day">30-Day Report</option>
                    <option value="90-day">90-Day Comprehensive</option>
                  </select>
                </div>
                
                <div>
                  <label className="text-sm font-medium mb-2 block">Report Date</label>
                  <Calendar
                    mode="single"
                    selected={selectedDate}
                    onSelect={setSelectedDate}
                    className="rounded-md border"
                  />
                </div>
                
                <Button 
                  onClick={generateReport}
                  className="w-full primary-gradient"
                >
                  <FileText className="h-4 w-4 mr-2" />
                  Generate PDF Report
                </Button>
              </CardContent>
            </Card>

            {/* Premium Features */}
            <Card className="border-secondary/20 bg-secondary/5">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-secondary">
                  <Crown className="h-5 w-5" />
                  Premium Reports
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm">Detailed biomarker analysis</span>
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm">Physician-ready summaries</span>
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm">Trend predictions</span>
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <Button variant="outline" className="w-full mt-4">
                  Upgrade for Premium Reports
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Report Preview */}
          <div className="lg:col-span-2">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-xl">{currentReport.title}</CardTitle>
                    <CardDescription>Preview • {currentReport.period}</CardDescription>
                  </div>
                  <Badge variant="outline" className="text-primary">
                    Preview Mode
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <Tabs defaultValue="overview" className="w-full">
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="overview">Overview</TabsTrigger>
                    <TabsTrigger value="metrics">Metrics</TabsTrigger>
                    <TabsTrigger value="insights">Insights</TabsTrigger>
                  </TabsList>
                  
                  <TabsContent value="overview" className="mt-6">
                    <div className="space-y-6">
                      {/* Biohackher Age Section */}
                      <div className="text-center p-6 bg-gradient-to-r from-primary/10 to-secondary/10 rounded-lg">
                        <h3 className="text-lg font-semibold mb-2">Your Biohackher Age</h3>
                        <div className="text-4xl font-bold gradient-text mb-2">
                          {sampleMetrics.biohackherAge.current} years
                        </div>
                        <p className="text-sm text-muted-foreground">
                          {Math.abs(sampleMetrics.biohackherAge.trend)} years younger than last period
                        </p>
                      </div>

                      {/* Key Highlights */}
                      <div>
                        <h3 className="text-lg font-semibold mb-4">Key Highlights</h3>
                        <div className="space-y-2">
                          {currentReport.highlights.map((highlight, index) => (
                            <div key={index} className="flex items-center gap-3 p-3 bg-muted/30 rounded-lg">
                              <TrendingUp className="h-4 w-4 text-green-500" />
                              <span className="text-sm">{highlight}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </TabsContent>
                  
                  <TabsContent value="metrics" className="mt-6">
                    <div className="grid gap-4">
                      {Object.entries(sampleMetrics).map(([key, metric]) => (
                        <div key={key} className="flex items-center justify-between p-4 border rounded-lg">
                          <div>
                            <h3 className="font-medium capitalize">
                              {key.replace(/([A-Z])/g, ' $1').trim()}
                            </h3>
                            <p className="text-sm text-muted-foreground">
                              Current period average
                            </p>
                          </div>
                          <div className="text-right">
                            <div className="text-lg font-semibold">
                              {key === 'biohackherAge' ? `${metric.current} yrs` : `${metric.current}%`}
                            </div>
                            <div className={`text-sm flex items-center ${
                              metric.trend > 0 ? 'text-green-600' : 'text-red-600'
                            }`}>
                              {metric.trend > 0 ? '↗' : '↘'} {Math.abs(metric.trend)}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </TabsContent>
                  
                  <TabsContent value="insights" className="mt-6">
                    <div className="space-y-6">
                      <div>
                        <h3 className="text-lg font-semibold mb-4">Personalised Recommendations</h3>
                        <div className="space-y-3">
                          {currentReport.recommendations.map((rec, index) => (
                            <div key={index} className="p-4 bg-primary/5 border-l-4 border-primary rounded-r-lg">
                              <p className="text-sm">{rec}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                      
                      <div className="p-4 bg-muted/30 rounded-lg">
                        <h4 className="font-medium mb-2">Next Steps</h4>
                        <ul className="text-sm space-y-1 text-muted-foreground">
                          <li>• Schedule follow-up biomarker testing</li>
                          <li>• Continue current successful protocols</li>
                          <li>• Consider consultation with healthcare provider</li>
                          <li>• Set goals for next measurement period</li>
                        </ul>
                      </div>
                    </div>
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Reports;