import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Calendar } from "@/components/ui/calendar";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { FileText, Download, TrendingUp, Crown, Lock, Activity, Heart, Moon, Brain, Users, Utensils } from "lucide-react";
import { format } from "date-fns";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import Navigation from "@/components/Navigation";

const Reports = () => {
  const [selectedDate, setSelectedDate] = useState<Date | undefined>(new Date());
  const [reportType, setReportType] = useState("30-day");
  const [historicalData, setHistoricalData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    fetchHistoricalData();
  }, []);

  const fetchHistoricalData = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        toast({
          title: "Authentication Required",
          description: "Please sign in to view your reports.",
          variant: "destructive"
        });
        setLoading(false);
        return;
      }

      const { data, error } = await supabase
        .from('daily_scores')
        .select('*')
        .eq('user_id', user.id)
        .order('date', { ascending: false })
        .limit(30);

      if (error) throw error;

      setHistoricalData(data || []);
    } catch (error) {
      console.error('Error fetching historical data:', error);
      toast({
        title: "Error",
        description: "Failed to load historical data.",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const sampleMetrics = {
    biohackherAge: { current: 34, trend: -2 },
    sleepScore: { current: 78, trend: 5 },
    hrv: { current: 65, trend: 8 },
    proteinIntake: { current: 85, trend: 12 },
    symptomScore: { current: 25, trend: -15 }
  };

  const reportData = {
    "30-day": {
      title: "30-Day Longevity Report", 
      period: "March 2024",
      highlights: [
        "Biohackher Age improved by 2 years",
        "Sleep quality increased 15%", 
        "Hot flash frequency reduced 40%",
        "Protein targets met 85% of days"
      ],
      recommendations: [
        "Continue current sleep optimisation protocol",
        "Increase cold exposure frequency to 4x/week",
        "Add leucine supplementation to plant-based meals"
      ]
    },
    "90-day": {
      title: "90-Day Comprehensive Report",
      period: "Jan-Mar 2024", 
      highlights: [
        "Overall wellness score improved 32%",
        "Energy levels stabilized across cycle phases",
        "Reduced inflammatory markers by 25%",
        "Achieved target protein intake 80% of quarter"
      ],
      recommendations: [
        "Consider HRT consultation for symptom optimisation",
        "Implement structured strength training program",
        "Add targeted micronutrient testing"
      ]
    }
  };

  const currentReport = reportData[reportType as keyof typeof reportData];

  const generateReport = () => {
    // In real app, this would generate and download actual PDF
    const reportContent = `
BIOHACKHER LONGEVITY REPORT
${currentReport.title}
Period: ${currentReport.period}

EXECUTIVE SUMMARY
Your biohacking journey shows significant progress across multiple biomarkers.
Key improvements in sleep optimisation and symptom management protocols.

BIOHACKHER AGE ANALYSIS
Current Age: ${sampleMetrics.biohackherAge.current} years
Improvement: ${Math.abs(sampleMetrics.biohackherAge.trend)} years younger
Factors: Sleep quality, HRV training, nutrition optimisation

KEY METRICS SUMMARY
• Sleep Score: ${sampleMetrics.sleepScore.current}% (↑${sampleMetrics.sleepScore.trend}%)
• HRV: ${sampleMetrics.hrv.current}ms (↑${sampleMetrics.hrv.trend}%)  
• Protein Compliance: ${sampleMetrics.proteinIntake.current}% (↑${sampleMetrics.proteinIntake.trend}%)
• Symptom Score: ${sampleMetrics.symptomScore.current}/100 (↓${Math.abs(sampleMetrics.symptomScore.trend)}%)

HIGHLIGHTS
${currentReport.highlights.map(h => `• ${h}`).join('\n')}

RECOMMENDATIONS
${currentReport.recommendations.map(r => `• ${r}`).join('\n')}

PROTOCOLS COMPLETED
• Red Light Therapy: 24/30 sessions
• Cold Exposure: 18/30 sessions  
• HRV Breathwork: 28/30 sessions
• Sleep Optimisation: 27/30 nights

Generated by Biohackher - Women's Longevity Coach
Report ID: BH-${Date.now()}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportType}-biohackher-report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2 gradient-text">Progress Reports</h1>
          <p className="text-muted-foreground">
            Comprehensive analysis of your biohacking journey and longevity metrics
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Report Configuration */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Generate Report</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-sm font-medium mb-2 block">Report Type</label>
                  <select 
                    value={reportType}
                    onChange={(e) => setReportType(e.target.value)}
                    className="w-full p-2 border rounded-md"
                  >
                    <option value="30-day">30-Day Report</option>
                    <option value="90-day">90-Day Comprehensive</option>
                  </select>
                </div>
                
                <div>
                  <label className="text-sm font-medium mb-2 block">Report Date</label>
                  <Calendar
                    mode="single"
                    selected={selectedDate}
                    onSelect={setSelectedDate}
                    className="rounded-md border"
                  />
                </div>
                
                <Button 
                  onClick={generateReport}
                  className="w-full primary-gradient"
                >
                  <FileText className="h-4 w-4 mr-2" />
                  Generate PDF Report
                </Button>
              </CardContent>
            </Card>

            {/* Premium Features */}
            <Card className="border-secondary/20 bg-secondary/5">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-secondary">
                  <Crown className="h-5 w-5" />
                  Premium Reports
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm">Detailed biomarker analysis</span>
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm">Physician-ready summaries</span>
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm">Trend predictions</span>
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <Button variant="outline" className="w-full mt-4">
                  Upgrade for Premium Reports
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Historical Data Display */}
          <div className="lg:col-span-2">
            <Card>
              <CardHeader>
                <CardTitle className="text-xl">Historical Data</CardTitle>
                <CardDescription>Detailed view of your past entries for investigation</CardDescription>
              </CardHeader>
              <CardContent>
                {loading ? (
                  <div className="text-center py-8">Loading your data...</div>
                ) : historicalData.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    No data found. Start tracking your daily metrics to see reports here.
                  </div>
                ) : (
                  <div className="space-y-4">
                    <Accordion type="single" collapsible className="w-full">
                      {historicalData.map((entry, index) => (
                        <AccordionItem key={entry.id} value={`item-${index}`}>
                          <AccordionTrigger className="text-left">
                            <div className="flex items-center justify-between w-full pr-4">
                              <div className="flex items-center gap-4">
                                <span className="font-medium">
                                  {format(new Date(entry.date), 'dd/MM/yyyy')}
                                </span>
                                <Badge variant="outline" className={
                                  entry.color_code === 'green' ? 'border-green-500 text-green-600' :
                                  entry.color_code === 'yellow' ? 'border-yellow-500 text-yellow-600' :
                                  'border-red-500 text-red-600'
                                }>
                                  LIS: {entry.longevity_impact_score}
                                </Badge>
                              </div>
                              <span className={`text-sm font-medium ${
                                entry.biological_age_impact > 0 ? 'text-green-600' : 
                                entry.biological_age_impact < 0 ? 'text-red-600' : 'text-yellow-600'
                              }`}>
                                {entry.biological_age_impact > 0 ? '-' : '+'}
                                {Math.abs(entry.biological_age_impact)} days
                              </span>
                            </div>
                          </AccordionTrigger>
                          <AccordionContent>
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pt-4">
                              {/* Sleep Data */}
                              <div className="p-4 border rounded-lg">
                                <div className="flex items-center gap-2 mb-3">
                                  <Moon className="h-4 w-4 text-blue-500" />
                                  <h4 className="font-semibold">Sleep Quality</h4>
                                  <Badge variant="secondary">{Math.round(entry.sleep_score || 0)}</Badge>
                                </div>
                                <div className="space-y-2 text-sm">
                                  <div>Total Sleep: {entry.total_sleep_hours}h</div>
                                  <div>REM Sleep: {entry.rem_hours}h</div>
                                  <div>Deep Sleep: {entry.deep_sleep_hours}h</div>
                                </div>
                              </div>

                              {/* Stress Data */}
                              <div className="p-4 border rounded-lg">
                                <div className="flex items-center gap-2 mb-3">
                                  <Heart className="h-4 w-4 text-red-500" />
                                  <h4 className="font-semibold">Stress</h4>
                                  <Badge variant="secondary">{Math.round(entry.stress_score || 0)}</Badge>
                                </div>
                                <div className="space-y-2 text-sm">
                                  <div>HRV: {entry.hrv}ms</div>
                                  <div>Stress Level: {entry.self_reported_stress}/10</div>
                                </div>
                              </div>

                              {/* Activity Data */}
                              <div className="p-4 border rounded-lg">
                                <div className="flex items-center gap-2 mb-3">
                                  <Activity className="h-4 w-4 text-green-500" />
                                  <h4 className="font-semibold">Activity</h4>
                                  <Badge variant="secondary">{Math.round(entry.physical_activity_score || 0)}</Badge>
                                </div>
                                <div className="space-y-2 text-sm">
                                  <div>Active Minutes: {entry.active_minutes}min</div>
                                  <div>Steps: {entry.steps?.toLocaleString()}</div>
                                  <div>Type: {entry.activity_type}</div>
                                  <div>Intensity: {entry.activity_intensity}/10</div>
                                </div>
                              </div>

                              {/* Nutrition Data */}
                              <div className="p-4 border rounded-lg">
                                <div className="flex items-center gap-2 mb-3">
                                  <Utensils className="h-4 w-4 text-orange-500" />
                                  <h4 className="font-semibold">Nutrition</h4>
                                  <Badge variant="secondary">{Math.round(entry.nutrition_score || 0)}</Badge>
                                </div>
                                <div className="space-y-2 text-sm">
                                  {entry.nutritional_detailed_score !== null ? (
                                    <>
                                      <div>Detailed Score: {entry.nutritional_detailed_score} ({entry.nutritional_grade})</div>
                                      <Badge variant="outline" className="text-xs">Detailed Tracking</Badge>
                                    </>
                                  ) : (
                                    <>
                                      <div>Meal Quality: {entry.meal_quality}/10</div>
                                      <Badge variant="outline" className="text-xs">Simple Tracking</Badge>
                                    </>
                                  )}
                                </div>
                              </div>

                              {/* Social Data */}
                              <div className="p-4 border rounded-lg">
                                <div className="flex items-center gap-2 mb-3">
                                  <Users className="h-4 w-4 text-purple-500" />
                                  <h4 className="font-semibold">Social</h4>
                                  <Badge variant="secondary">{Math.round(entry.social_connections_score || 0)}</Badge>
                                </div>
                                <div className="space-y-2 text-sm">
                                  <div>Interaction Quality: {entry.social_interaction_quality}/10</div>
                                  <div>Social Time: {entry.social_time_minutes}min</div>
                                </div>
                              </div>

                              {/* Cognitive Data */}
                              <div className="p-4 border rounded-lg">
                                <div className="flex items-center gap-2 mb-3">
                                  <Brain className="h-4 w-4 text-indigo-500" />
                                  <h4 className="font-semibold">Cognitive</h4>
                                  <Badge variant="secondary">{Math.round(entry.cognitive_engagement_score || 0)}</Badge>
                                </div>
                                <div className="space-y-2 text-sm">
                                  <div>Meditation: {entry.meditation_minutes}min</div>
                                  <div>Learning: {entry.learning_minutes}min</div>
                                </div>
                              </div>
                            </div>
                            
                            <div className="mt-4 pt-4 border-t">
                              <div className="flex items-center justify-between text-sm text-muted-foreground">
                                <span>Input Method: {entry.input_mode || 'manual'}</span>
                                <span>Updated: {format(new Date(entry.updated_at), 'HH:mm on dd/MM/yyyy')}</span>
                              </div>
                            </div>
                          </AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Reports;