export const FEATURE_FLAGS = {
  TRIPLE_HERO_ENABLED: true,
  SOCIAL_PROOF_ENABLED: true,
  ASSESSMENT_CONSTELLATION_ENABLED: true,
  MASTER_DASHBOARD_ENABLED: true,
  SHOP_SMART_RECOMMENDATIONS: true,
  BETA_TESTING_ENABLED: true,
} as const;
