-- Seed products table with initial product data

-- Sleep Products
INSERT INTO products (name, description, detailed_description, category, price_gbp, price_usd, price_cad, price_aud, brand, image_url, benefits, usage_instructions, target_symptoms, evidence_level, display_order, is_active) VALUES
(
  'Magnesium Glycinate 400mg',
  'High-absorption magnesium for deep, restorative sleep and muscle relaxation',
  'Magnesium glycinate is one of the most bioavailable forms of magnesium, offering superior absorption compared to other magnesium supplements. This essential mineral plays a crucial role in over 300 enzymatic reactions in the body, including those that regulate sleep, muscle function, and nervous system health.',
  'sleep',
  20.99,
  24.99,
  32.99,
  36.99,
  'Pure Encapsulations',
  '/api/placeholder/300/300',
  '["Improving sleep onset", "Reducing muscle tension", "Supporting nervous system", "Promoting relaxation", "Supporting bone health"]',
  'Take 2 capsules 30-60 minutes before bed with water',
  '["sleep", "anxiety", "muscle-tension", "restlessness", "insomnia"]',
  'gold',
  1,
  true
),
(
  'Slow-Release Melatonin 3mg',
  'Extended-release melatonin for sustained sleep throughout the night',
  'This slow-release formulation ensures a gradual release of melatonin throughout the night, helping maintain consistent sleep levels and reducing nighttime awakenings. Melatonin is a natural hormone that regulates the sleep-wake cycle.',
  'sleep',
  16.99,
  19.99,
  25.99,
  28.99,
  'Natrol',
  '/api/placeholder/300/300',
  '["Regulating circadian rhythm", "Extending sleep duration", "Reducing wake-ups", "Supporting jet lag recovery"]',
  'Take 1 tablet 1-2 hours before bedtime',
  '["sleep", "jet-lag", "shift-work", "insomnia"]',
  'gold',
  2,
  true
),
(
  'L-Theanine 200mg',
  'Amino acid that promotes relaxation without drowsiness',
  'L-Theanine is a unique amino acid found naturally in green tea that promotes a state of calm alertness. It supports healthy brain function by increasing alpha brain wave activity and modulating neurotransmitter levels.',
  'sleep',
  19.99,
  22.99,
  29.99,
  33.99,
  'NOW Foods',
  '/api/placeholder/300/300',
  '["Promoting calm alertness", "Reducing stress", "Improving sleep quality", "Supporting focus"]',
  'Take 1-2 capsules before bed or during stressful periods',
  '["sleep", "anxiety", "stress", "restlessness"]',
  'silver',
  3,
  true
);

-- Hot Flashes / Hormone Balance Products
INSERT INTO products (name, description, detailed_description, category, price_gbp, price_usd, price_cad, price_aud, brand, image_url, benefits, usage_instructions, target_symptoms, evidence_level, display_order, is_active) VALUES
(
  'Black Cohosh Extract 80mg',
  'Standardized extract to help manage menopausal symptoms naturally',
  'Black Cohosh has been traditionally used for centuries to support women''s health, particularly during menopause. This standardized extract ensures consistent levels of active compounds shown to help reduce hot flash frequency and intensity.',
  'hot-flashes',
  23.99,
  27.99,
  36.99,
  40.99,
  'Gaia Herbs',
  '/api/placeholder/300/300',
  '["Reducing hot flash frequency", "Supporting hormone balance", "Improving mood", "Supporting sleep quality"]',
  'Take 1 capsule twice daily with meals',
  '["hot-flashes", "mood-swings", "night-sweats", "menopause"]',
  'gold',
  1,
  true
),
(
  'Red Clover Isoflavones',
  'Natural phytoestrogens to support hormonal balance during menopause',
  'Red Clover contains naturally occurring isoflavones that act as gentle phytoestrogens, helping to support hormonal balance during perimenopause and menopause. These plant compounds may help maintain bone density and cardiovascular health.',
  'hot-flashes',
  18.99,
  21.99,
  28.99,
  32.99,
  'Nature''s Way',
  '/api/placeholder/300/300',
  '["Natural estrogen support", "Supporting bone health", "Supporting cardiovascular health", "Reducing hot flashes"]',
  'Take 2 capsules daily with food',
  '["hot-flashes", "bone-health", "heart-health", "menopause"]',
  'silver',
  2,
  true
);

-- Joint Pain Products
INSERT INTO products (name, description, detailed_description, category, price_gbp, price_usd, price_cad, price_aud, brand, image_url, benefits, usage_instructions, target_symptoms, evidence_level, display_order, is_active) VALUES
(
  'Turmeric Curcumin with Bioperine',
  'High-potency curcumin with black pepper extract for maximum absorption',
  'This premium formulation combines standardized curcumin extract with Bioperine (black pepper extract) to enhance absorption by up to 2000%. Curcumin is the active compound in turmeric known for its powerful anti-inflammatory and antioxidant properties.',
  'joint-pain',
  25.99,
  29.99,
  39.99,
  43.99,
  'NatureWise',
  '/api/placeholder/300/300',
  '["Powerful anti-inflammatory", "Relieving joint pain", "Supporting mobility", "Antioxidant support", "Supporting recovery"]',
  'Take 2 capsules daily with meals',
  '["joint-pain", "inflammation", "arthritis", "stiffness", "muscle-pain"]',
  'gold',
  1,
  true
),
(
  'Ultra-Pure Omega-3 Fish Oil',
  'High-potency EPA/DHA for inflammation reduction and joint health',
  'Molecularly distilled for purity, this premium omega-3 supplement provides high concentrations of EPA and DHA fatty acids. These essential fats support joint health by reducing inflammation and promoting cardiovascular wellness.',
  'joint-pain',
  29.99,
  34.99,
  45.99,
  50.99,
  'Nordic Naturals',
  '/api/placeholder/300/300',
  '["Reducing inflammation", "Supporting joint mobility", "Supporting heart health", "Supporting brain function"]',
  'Take 2 softgels daily with meals',
  '["joint-pain", "inflammation", "heart-health", "arthritis"]',
  'gold',
  2,
  true
),
(
  'Glucosamine Chondroitin MSM',
  'Triple-action formula for comprehensive joint support and cartilage health',
  'This synergistic combination of glucosamine, chondroitin, and MSM provides comprehensive support for joint structure and function. These compounds work together to maintain cartilage integrity and reduce joint discomfort.',
  'joint-pain',
  22.99,
  26.99,
  35.99,
  39.99,
  'Doctor''s Best',
  '/api/placeholder/300/300',
  '["Supporting cartilage", "Improving joint flexibility", "Enhancing mobility", "Reducing stiffness"]',
  'Take 3 tablets daily with food',
  '["joint-pain", "cartilage-health", "mobility", "arthritis", "stiffness"]',
  'silver',
  3,
  true
);

-- Gut Health Products
INSERT INTO products (name, description, detailed_description, category, price_gbp, price_usd, price_cad, price_aud, brand, image_url, benefits, usage_instructions, target_symptoms, evidence_level, display_order, is_active) VALUES
(
  'Full-Spectrum Digestive Enzymes',
  'Comprehensive enzyme blend to support optimal digestion and nutrient absorption',
  'This broad-spectrum enzyme formula contains proteases, lipases, amylases, and other specialized enzymes to break down proteins, fats, and carbohydrates. Supports comfortable digestion and maximizes nutrient extraction from food.',
  'gut',
  26.99,
  31.99,
  41.99,
  46.99,
  'Enzymedica',
  '/api/placeholder/300/300',
  '["Improving digestion", "Reducing bloating", "Enhancing nutrient absorption", "Supporting comfortable eating", "Reducing gas"]',
  'Take 1-2 capsules with each meal',
  '["bloating", "indigestion", "nutrient-absorption", "gas", "discomfort"]',
  'gold',
  1,
  true
),
(
  '50 Billion CFU Probiotic',
  'Multi-strain probiotic for digestive health and immune support',
  'Contains 15 diverse probiotic strains including Lactobacillus and Bifidobacterium species to support a healthy gut microbiome. Shelf-stable formula with delayed-release capsules for maximum viability.',
  'gut',
  33.99,
  39.99,
  52.99,
  58.99,
  'Garden of Life',
  '/api/placeholder/300/300',
  '["Supporting digestive balance", "Supporting immune system", "Supporting mood regulation", "Promoting gut health", "Reducing bloating"]',
  'Take 1 capsule daily with or without food',
  '["gut-health", "immunity", "mood", "bloating", "digestive-issues"]',
  'gold',
  2,
  true
),
(
  'Prebiotic Fibre Complex',
  'Soluble and insoluble fibre blend to support healthy digestion',
  'Combines multiple fiber sources including psyllium husk, inulin, and acacia fiber to feed beneficial gut bacteria and support regular bowel movements. Gentle formula suitable for sensitive digestive systems.',
  'gut',
  19.99,
  23.99,
  31.99,
  35.99,
  'Heather''s Tummy Care',
  '/api/placeholder/300/300',
  '["Supporting regularity", "Feeding beneficial bacteria", "Supporting blood sugar balance", "Promoting satiety"]',
  'Mix 1 scoop in 8oz water daily, preferably in the morning',
  '["constipation", "gut-health", "blood-sugar", "irregularity"]',
  'silver',
  3,
  true
),
(
  'Betaine HCl with Pepsin',
  'Supports protein digestion and stomach acid production for optimal nutrient breakdown',
  'Provides hydrochloric acid and pepsin to support healthy stomach acidity and protein digestion. Particularly beneficial for those with low stomach acid production, which can lead to bloating and poor nutrient absorption.',
  'gut',
  23.99,
  27.99,
  36.99,
  40.99,
  'Thorne',
  '/api/placeholder/300/300',
  '["Supporting protein digestion", "Enhancing stomach acid production", "Improving nutrient breakdown", "Reducing bloating"]',
  'Take 1 capsule with protein-containing meals. Do not take on an empty stomach.',
  '["bloating", "protein-digestion", "nutrient-absorption", "indigestion"]',
  'silver',
  4,
  true
),
(
  'L-Glutamine Powder',
  'Pure L-glutamine amino acid to support intestinal lining and gut barrier function',
  'L-Glutamine is the most abundant amino acid in the body and serves as the primary fuel source for intestinal cells. Supports gut barrier integrity and may help maintain a healthy intestinal lining.',
  'gut',
  25.99,
  29.99,
  39.99,
  43.99,
  'NOW Foods',
  '/api/placeholder/300/300',
  '["Supporting gut lining", "Enhancing intestinal barrier", "Supporting recovery", "Promoting gut healing"]',
  'Take 5g (approximately 1 teaspoon) twice daily between meals, mixed in water or juice',
  '["gut-health", "intestinal-permeability", "recovery", "leaky-gut"]',
  'silver',
  5,
  true
),
(
  'Swedish Bitters Complex',
  'Traditional herbal blend with gentian root, dandelion, and artichoke to stimulate digestion',
  'Time-honored European formula combining bitter herbs that naturally stimulate digestive enzyme and bile production. Supports appetite regulation and comfortable digestion when taken before meals.',
  'gut',
  20.99,
  24.99,
  32.99,
  36.99,
  'Gaia Herbs',
  '/api/placeholder/300/300',
  '["Stimulating digestive enzymes", "Supporting appetite", "Enhancing digestion", "Supporting bile production"]',
  'Take 1-2 droppers in water, 15 minutes before each meal',
  '["bloating", "poor-digestion", "appetite", "indigestion"]',
  'bronze',
  6,
  true
),
(
  'Gentian Root Extract',
  'Pure gentian root extract to support digestive function and bile production',
  'Gentian root is one of the most bitter herbs known and has been used traditionally to support healthy digestion. The bitter compounds help stimulate digestive secretions and promote optimal bile flow.',
  'gut',
  18.99,
  21.99,
  28.99,
  32.99,
  'Planetary Herbals',
  '/api/placeholder/300/300',
  '["Supporting bile production", "Enhancing digestive function", "Stimulating appetite", "Supporting liver health"]',
  'Take 1 capsule 20 minutes before meals',
  '["poor-digestion", "bloating", "appetite", "sluggish-digestion"]',
  'bronze',
  7,
  true
);

-- Brain Fog / Cognitive Support Products
INSERT INTO products (name, description, detailed_description, category, price_gbp, price_usd, price_cad, price_aud, brand, image_url, benefits, usage_instructions, target_symptoms, evidence_level, display_order, is_active) VALUES
(
  'Lion''s Mane Mushroom Extract',
  'Organic mushroom extract to support cognitive function and nerve health',
  'Lion''s Mane contains unique compounds called hericenones and erinacines that may support nerve growth factor production. This medicinal mushroom has been used traditionally to support brain health, memory, and mental clarity.',
  'brain-fog',
  24.99,
  28.99,
  38.99,
  42.99,
  'Host Defense',
  '/api/placeholder/300/300',
  '["Supporting cognitive function", "Supporting nerve growth factor", "Enhancing mental clarity", "Supporting memory", "Promoting focus"]',
  'Take 2 capsules daily with food',
  '["brain-fog", "memory", "focus", "concentration", "mental-clarity"]',
  'silver',
  1,
  true
),
(
  'Active B-Complex',
  'Methylated B vitamins for energy production and brain function',
  'Features bioactive forms of B vitamins including methylfolate and methylcobalamin that are readily usable by the body. B vitamins are essential cofactors in energy metabolism, neurotransmitter synthesis, and nervous system function.',
  'brain-fog',
  21.99,
  25.99,
  34.99,
  38.99,
  'Thorne',
  '/api/placeholder/300/300',
  '["Supporting mental energy", "Supporting neurotransmitters", "Building stress resilience", "Supporting mood", "Enhancing focus"]',
  'Take 1 capsule daily with breakfast',
  '["brain-fog", "energy", "mood", "fatigue", "concentration"]',
  'gold',
  2,
  true
);