// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcjqdtlqhbmyjckbfokz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjanFkdGxxaGJteWpja2Jmb2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTQwNDgsImV4cCI6MjA3NDA5MDA0OH0.dBF-kFOjk06XJCIB4NmB8rN3JkscNJhQdfwT52b_ViY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});